[package]
name = "playlist-sync"
version = "0.1.0"
edition = "2024"

[dependencies]

[workspace]
members = [
    "src/crates/common",
    "src/crates/local-music-parser",
    "src/crates/spotify-parser",
    "src/apps/cli",
]
resolver = "2"
